version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'gomod'
    directory: '/apps/graphql-api'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'gomod'
    directory: '/apps/workers'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'gomod'
    directory: '/packages/shared-go'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
