package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"

	"project-neo/graphql-api/graph/generated"
	"project-neo/graphql-api/internal/auth"
	"project-neo/shared/model"

	"github.com/google/uuid"
)

// UpsertUser is the resolver for the upsertUser field.
func (r *mutationResolver) UpsertUser(ctx context.Context, input model.UpsertUserInput) (*model.User, error) {
	userID, err := auth.UserIDFromCtx(ctx)
	if err != nil {
		return nil, err
	}
	return r.Resolver.Users.Upsert(ctx, userID, input)
}

// CreateRide is the resolver for the createRide field.
func (r *mutationResolver) CreateRide(ctx context.Context, input model.CreateRideInput) (*model.Ride, error) {
	userID, err := auth.UserIDFromCtx(ctx)
	if err != nil {
		return nil, err
	}
	return r.Resolver.Rides.Create(ctx, userID, input)
}

// UpdateRide is the resolver for the updateRide field.
func (r *mutationResolver) UpdateRide(ctx context.Context, id uuid.UUID, input model.UpdateRideInput) (*model.Ride, error) {
	userID, err := auth.UserIDFromCtx(ctx)
	if err != nil {
		return nil, err
	}
	return r.Resolver.Rides.Update(ctx, id, userID, input)
}

// CancelRide is the resolver for the cancelRide field.
func (r *mutationResolver) CancelRide(ctx context.Context, id uuid.UUID) (*model.Ride, error) {
	userID, err := auth.UserIDFromCtx(ctx)
	if err != nil {
		return nil, err
	}
	return r.Resolver.Rides.Cancel(ctx, id, userID)
}

// AcceptMatch is the resolver for the acceptMatch field.
func (r *mutationResolver) AcceptMatch(ctx context.Context, rideID uuid.UUID) (*model.Match, error) {
	driverID, err := auth.UserIDFromCtx(ctx)
	if err != nil {
		return nil, err
	}
	ride, err := r.Resolver.Rides.GetByID(ctx, rideID)
	if err != nil {
		return nil, err
	}
	if ride.PosterUserID == nil {
		return nil, fmt.Errorf("ride poster is not a registered user — contact via WhatsApp relay")
	}
	if ride.Status != model.RideStatusAvailable {
		return nil, fmt.Errorf("ride is not available")
	}
	match, err := r.Resolver.Matches.Create(ctx, rideID, *ride.PosterUserID, driverID)
	if err != nil {
		return nil, err
	}
	match, err = r.Resolver.Matches.UpdateStatus(ctx, match.ID, model.MatchStatusAccepted)
	if err != nil {
		return nil, err
	}
	if _, err := r.Resolver.Rides.SetStatus(ctx, rideID, model.RideStatusMatched); err != nil {
		return nil, err
	}
	return match, nil
}

// RejectMatch is the resolver for the rejectMatch field.
func (r *mutationResolver) RejectMatch(ctx context.Context, matchID uuid.UUID) (*model.Match, error) {
	_, err := auth.UserIDFromCtx(ctx)
	if err != nil {
		return nil, err
	}
	return r.Resolver.Matches.UpdateStatus(ctx, matchID, model.MatchStatusRejected)
}

// CompleteMatch is the resolver for the completeMatch field.
func (r *mutationResolver) CompleteMatch(ctx context.Context, matchID uuid.UUID) (*model.Match, error) {
	_, err := auth.UserIDFromCtx(ctx)
	if err != nil {
		return nil, err
	}
	match, err := r.Resolver.Matches.UpdateStatus(ctx, matchID, model.MatchStatusCompleted)
	if err != nil {
		return nil, err
	}
	if _, err := r.Resolver.Rides.SetStatus(ctx, match.RideID, model.RideStatusCompleted); err != nil {
		return nil, err
	}
	return match, nil
}

// CancelMatch is the resolver for the cancelMatch field.
func (r *mutationResolver) CancelMatch(ctx context.Context, matchID uuid.UUID) (*model.Match, error) {
	_, err := auth.UserIDFromCtx(ctx)
	if err != nil {
		return nil, err
	}
	match, err := r.Resolver.Matches.UpdateStatus(ctx, matchID, model.MatchStatusCancelled)
	if err != nil {
		return nil, err
	}
	if _, err := r.Resolver.Rides.SetStatus(ctx, match.RideID, model.RideStatusAvailable); err != nil {
		return nil, err
	}
	return match, nil
}

// CreateGroup is the resolver for the createGroup field.
func (r *mutationResolver) CreateGroup(ctx context.Context, input model.CreateGroupInput) (*model.Group, error) {
	_, err := auth.UserIDFromCtx(ctx)
	if err != nil {
		return nil, err
	}
	return r.Resolver.Groups.Create(ctx, input)
}

// UpsertLocationContext is the resolver for the upsertLocationContext field.
func (r *mutationResolver) UpsertLocationContext(ctx context.Context, input model.UpsertLocationContextInput) (*model.LocationContext, error) {
	_, err := auth.UserIDFromCtx(ctx)
	if err != nil {
		return nil, err
	}
	return r.Resolver.Groups.UpsertLocationContext(ctx, input)
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
