package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"

	"github.com/google/uuid"
	"project-neo/graphql-api/graph/generated"
	"project-neo/graphql-api/internal/auth"
	model1 "project-neo/shared/model"
)

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	return "ok", nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model1.User, error) {
	userID, err := auth.UserIDFromCtx(ctx)
	if err != nil {
		return nil, err
	}
	return r.Resolver.Users.GetByID(ctx, userID)
}

// Rides is the resolver for the rides field.
func (r *queryResolver) Rides(ctx context.Context, groupID uuid.UUID, typeArg *model1.RideType, status *model1.RideStatus, limit *int, offset *int) ([]*model1.Ride, error) {
	_, err := auth.UserIDFromCtx(ctx)
	if err != nil {
		return nil, err
	}
	filter := model1.RideFilter{
		GroupID:    groupID,
		Type:       typeArg,
		Status:     status,
		Pagination: model1.NewPagination(limit, offset),
	}
	return r.Resolver.Rides.List(ctx, filter)
}

// Ride is the resolver for the ride field.
func (r *queryResolver) Ride(ctx context.Context, id uuid.UUID) (*model1.Ride, error) {
	_, err := auth.UserIDFromCtx(ctx)
	if err != nil {
		return nil, err
	}
	return r.Resolver.Rides.GetByID(ctx, id)
}

// MyRides is the resolver for the myRides field.
func (r *queryResolver) MyRides(ctx context.Context, limit *int, offset *int) ([]*model1.Ride, error) {
	userID, err := auth.UserIDFromCtx(ctx)
	if err != nil {
		return nil, err
	}
	return r.Resolver.Rides.ListByUser(ctx, userID, model1.NewPagination(limit, offset))
}

// MyMatches is the resolver for the myMatches field.
func (r *queryResolver) MyMatches(ctx context.Context, limit *int, offset *int) ([]*model1.Match, error) {
	userID, err := auth.UserIDFromCtx(ctx)
	if err != nil {
		return nil, err
	}
	return r.Resolver.Matches.ListByUser(ctx, userID, model1.NewPagination(limit, offset))
}

// Groups is the resolver for the groups field.
func (r *queryResolver) Groups(ctx context.Context) ([]*model1.Group, error) {
	return r.Resolver.Groups.List(ctx)
}

// Group is the resolver for the group field.
func (r *queryResolver) Group(ctx context.Context, id uuid.UUID) (*model1.Group, error) {
	return r.Resolver.Groups.GetByID(ctx, id)
}

// Locations is the resolver for the locations field.
func (r *queryResolver) Locations(ctx context.Context, query string) ([]*model1.Location, error) {
	return r.Resolver.Locations.Search(ctx, query)
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
