package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	"project-neo/graphql-api/graph/generated"
	model1 "project-neo/graphql-api/internal/model"

	"github.com/google/uuid"
)

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	panic(fmt.Errorf("not implemented: Health - health"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model1.User, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// Rides is the resolver for the rides field.
func (r *queryResolver) Rides(ctx context.Context, groupID uuid.UUID, typeArg *model1.RideType, status *model1.RideStatus, limit *int, offset *int) ([]*model1.Ride, error) {
	panic(fmt.Errorf("not implemented: Rides - rides"))
}

// Ride is the resolver for the ride field.
func (r *queryResolver) Ride(ctx context.Context, id uuid.UUID) (*model1.Ride, error) {
	panic(fmt.Errorf("not implemented: Ride - ride"))
}

// MyRides is the resolver for the myRides field.
func (r *queryResolver) MyRides(ctx context.Context, limit *int, offset *int) ([]*model1.Ride, error) {
	panic(fmt.Errorf("not implemented: MyRides - myRides"))
}

// MyMatches is the resolver for the myMatches field.
func (r *queryResolver) MyMatches(ctx context.Context, limit *int, offset *int) ([]*model1.Match, error) {
	panic(fmt.Errorf("not implemented: MyMatches - myMatches"))
}

// Groups is the resolver for the groups field.
func (r *queryResolver) Groups(ctx context.Context) ([]*model1.Group, error) {
	panic(fmt.Errorf("not implemented: Groups - groups"))
}

// Group is the resolver for the group field.
func (r *queryResolver) Group(ctx context.Context, id uuid.UUID) (*model1.Group, error) {
	panic(fmt.Errorf("not implemented: Group - group"))
}

// Locations is the resolver for the locations field.
func (r *queryResolver) Locations(ctx context.Context, query string) ([]*model1.Location, error) {
	panic(fmt.Errorf("not implemented: Locations - locations"))
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
