package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"

	"github.com/google/uuid"
	"project-neo/graphql-api/graph/generated"
	"project-neo/graphql-api/internal/auth"
	sharedmodel "project-neo/shared/model"
)

// RideAdded is the resolver for the rideAdded field.
func (r *subscriptionResolver) RideAdded(ctx context.Context, groupID uuid.UUID) (<-chan *sharedmodel.Ride, error) {
	if _, err := auth.UserIDFromCtx(ctx); err != nil {
		return nil, err
	}
	ch := make(chan *sharedmodel.Ride, 4)
	events, cancel := r.Resolver.Broker.SubscribeRideAdded()

	go func() {
		defer cancel()
		defer close(ch)
		for {
			select {
			case <-ctx.Done():
				return
			case e, ok := <-events:
				if !ok {
					return
				}
				if e.GroupID == groupID.String() {
					select {
					case ch <- e.Ride:
					case <-ctx.Done():
						return
					}
				}
			}
		}
	}()
	return ch, nil
}

// RideStatusChanged is the resolver for the rideStatusChanged field.
func (r *subscriptionResolver) RideStatusChanged(ctx context.Context, groupID uuid.UUID) (<-chan *sharedmodel.Ride, error) {
	if _, err := auth.UserIDFromCtx(ctx); err != nil {
		return nil, err
	}
	ch := make(chan *sharedmodel.Ride, 4)
	events, cancel := r.Resolver.Broker.SubscribeRideUpdated()

	go func() {
		defer cancel()
		defer close(ch)
		for {
			select {
			case <-ctx.Done():
				return
			case e, ok := <-events:
				if !ok {
					return
				}
				if e.GroupID == groupID.String() {
					select {
					case ch <- e.Ride:
					case <-ctx.Done():
						return
					}
				}
			}
		}
	}()
	return ch, nil
}

// MatchStatusChanged is the resolver for the matchStatusChanged field.
func (r *subscriptionResolver) MatchStatusChanged(ctx context.Context) (<-chan *sharedmodel.Match, error) {
	userID, err := auth.UserIDFromCtx(ctx)
	if err != nil {
		return nil, err
	}
	ch := make(chan *sharedmodel.Match, 4)
	events, cancel := r.Resolver.Broker.SubscribeMatchUpdated()

	go func() {
		defer cancel()
		defer close(ch)
		for {
			select {
			case <-ctx.Done():
				return
			case m, ok := <-events:
				if !ok {
					return
				}
				if m.RiderID == userID || m.DriverID == userID {
					select {
					case ch <- m:
					case <-ctx.Done():
						return
					}
				}
			}
		}
	}()
	return ch, nil
}

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type subscriptionResolver struct{ *Resolver }
