package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	"project-neo/graphql-api/graph/generated"
	model1 "project-neo/graphql-api/internal/model"

	"github.com/google/uuid"
)

// RideAdded is the resolver for the rideAdded field.
func (r *subscriptionResolver) RideAdded(ctx context.Context, groupID uuid.UUID) (<-chan *model1.Ride, error) {
	panic(fmt.Errorf("not implemented: RideAdded - rideAdded"))
}

// RideStatusChanged is the resolver for the rideStatusChanged field.
func (r *subscriptionResolver) RideStatusChanged(ctx context.Context, groupID uuid.UUID) (<-chan *model1.Ride, error) {
	panic(fmt.Errorf("not implemented: RideStatusChanged - rideStatusChanged"))
}

// MatchStatusChanged is the resolver for the matchStatusChanged field.
func (r *subscriptionResolver) MatchStatusChanged(ctx context.Context) (<-chan *model1.Match, error) {
	panic(fmt.Errorf("not implemented: MatchStatusChanged - matchStatusChanged"))
}

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type subscriptionResolver struct{ *Resolver }
