package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"

	"project-neo/graphql-api/graph/generated"
	model1 "project-neo/graphql-api/internal/model"
)

// LocationContexts is the resolver for the locationContexts field.
func (r *groupResolver) LocationContexts(ctx context.Context, obj *model1.Group) ([]*model1.LocationContext, error) {
	return r.Resolver.Groups.ListLocationContexts(ctx, obj.ID)
}

// Group is the resolver for the group field.
func (r *locationContextResolver) Group(ctx context.Context, obj *model1.LocationContext) (*model1.Group, error) {
	return r.Resolver.Groups.GetByID(ctx, obj.GroupID)
}

// Location is the resolver for the location field.
func (r *locationContextResolver) Location(ctx context.Context, obj *model1.LocationContext) (*model1.Location, error) {
	if obj.LocationID == nil {
		return nil, nil
	}
	return r.Resolver.Locations.GetByID(ctx, *obj.LocationID)
}

// Ride is the resolver for the ride field.
func (r *matchResolver) Ride(ctx context.Context, obj *model1.Match) (*model1.Ride, error) {
	return r.Resolver.Rides.GetByID(ctx, obj.RideID)
}

// Rider is the resolver for the rider field.
func (r *matchResolver) Rider(ctx context.Context, obj *model1.Match) (*model1.User, error) {
	return r.Resolver.Users.GetByID(ctx, obj.RiderID)
}

// Driver is the resolver for the driver field.
func (r *matchResolver) Driver(ctx context.Context, obj *model1.Match) (*model1.User, error) {
	return r.Resolver.Users.GetByID(ctx, obj.DriverID)
}

// Group is the resolver for the group field.
func (r *rideResolver) Group(ctx context.Context, obj *model1.Ride) (*model1.Group, error) {
	return r.Resolver.Groups.GetByID(ctx, obj.GroupID)
}

// FromLocationContext is the resolver for the fromLocationContext field.
func (r *rideResolver) FromLocationContext(ctx context.Context, obj *model1.Ride) (*model1.LocationContext, error) {
	if obj.FromLocationID == nil {
		return nil, nil
	}
	return r.Resolver.Groups.GetLocationContextByID(ctx, *obj.FromLocationID)
}

// ToLocationContext is the resolver for the toLocationContext field.
func (r *rideResolver) ToLocationContext(ctx context.Context, obj *model1.Ride) (*model1.LocationContext, error) {
	if obj.ToLocationID == nil {
		return nil, nil
	}
	return r.Resolver.Groups.GetLocationContextByID(ctx, *obj.ToLocationID)
}

// PostedBy is the resolver for the postedBy field.
func (r *rideResolver) PostedBy(ctx context.Context, obj *model1.Ride) (*model1.User, error) {
	if obj.PosterUserID == nil {
		return nil, nil
	}
	return r.Resolver.Users.GetByID(ctx, *obj.PosterUserID)
}

// Group returns generated.GroupResolver implementation.
func (r *Resolver) Group() generated.GroupResolver { return &groupResolver{r} }

// LocationContext returns generated.LocationContextResolver implementation.
func (r *Resolver) LocationContext() generated.LocationContextResolver {
	return &locationContextResolver{r}
}

// Match returns generated.MatchResolver implementation.
func (r *Resolver) Match() generated.MatchResolver { return &matchResolver{r} }

// Ride returns generated.RideResolver implementation.
func (r *Resolver) Ride() generated.RideResolver { return &rideResolver{r} }

type groupResolver struct{ *Resolver }
type locationContextResolver struct{ *Resolver }
type matchResolver struct{ *Resolver }
type rideResolver struct{ *Resolver }
