package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	"project-neo/graphql-api/graph/generated"
	"project-neo/graphql-api/graph/model"
)

// LocationContexts is the resolver for the locationContexts field.
func (r *groupResolver) LocationContexts(ctx context.Context, obj *model.Group) ([]*model.LocationContext, error) {
	panic(fmt.Errorf("not implemented: LocationContexts - locationContexts"))
}

// Group is the resolver for the group field.
func (r *locationContextResolver) Group(ctx context.Context, obj *model.LocationContext) (*model.Group, error) {
	panic(fmt.Errorf("not implemented: Group - group"))
}

// Location is the resolver for the location field.
func (r *locationContextResolver) Location(ctx context.Context, obj *model.LocationContext) (*model.Location, error) {
	panic(fmt.Errorf("not implemented: Location - location"))
}

// Ride is the resolver for the ride field.
func (r *matchResolver) Ride(ctx context.Context, obj *model.Match) (*model.Ride, error) {
	panic(fmt.Errorf("not implemented: Ride - ride"))
}

// Rider is the resolver for the rider field.
func (r *matchResolver) Rider(ctx context.Context, obj *model.Match) (*model.User, error) {
	panic(fmt.Errorf("not implemented: Rider - rider"))
}

// Driver is the resolver for the driver field.
func (r *matchResolver) Driver(ctx context.Context, obj *model.Match) (*model.User, error) {
	panic(fmt.Errorf("not implemented: Driver - driver"))
}

// Group is the resolver for the group field.
func (r *rideResolver) Group(ctx context.Context, obj *model.Ride) (*model.Group, error) {
	panic(fmt.Errorf("not implemented: Group - group"))
}

// FromLocationContext is the resolver for the fromLocationContext field.
func (r *rideResolver) FromLocationContext(ctx context.Context, obj *model.Ride) (*model.LocationContext, error) {
	panic(fmt.Errorf("not implemented: FromLocationContext - fromLocationContext"))
}

// ToLocationContext is the resolver for the toLocationContext field.
func (r *rideResolver) ToLocationContext(ctx context.Context, obj *model.Ride) (*model.LocationContext, error) {
	panic(fmt.Errorf("not implemented: ToLocationContext - toLocationContext"))
}

// PostedBy is the resolver for the postedBy field.
func (r *rideResolver) PostedBy(ctx context.Context, obj *model.Ride) (*model.User, error) {
	panic(fmt.Errorf("not implemented: PostedBy - postedBy"))
}

// Group returns generated.GroupResolver implementation.
func (r *Resolver) Group() generated.GroupResolver { return &groupResolver{r} }

// LocationContext returns generated.LocationContextResolver implementation.
func (r *Resolver) LocationContext() generated.LocationContextResolver {
	return &locationContextResolver{r}
}

// Match returns generated.MatchResolver implementation.
func (r *Resolver) Match() generated.MatchResolver { return &matchResolver{r} }

// Ride returns generated.RideResolver implementation.
func (r *Resolver) Ride() generated.RideResolver { return &rideResolver{r} }

type groupResolver struct{ *Resolver }
type locationContextResolver struct{ *Resolver }
type matchResolver struct{ *Resolver }
type rideResolver struct{ *Resolver }
